adb uninstall --user 0 com.android.stk
adb uninstall --user 0 com.facebook.services
adb uninstall --user 0 com.facebook.system
adb uninstall --user 0 com.facebook.appmanager
adb uninstall --user 0 com.google.android.apps.youtube.music
adb uninstall --user 0 com.google.ar.core
adb uninstall --user 0 com.redteamobile.roaming
adb uninstall --user 0 com.google.android.videos
adb uninstall --user 0 com.google.android.apps.work.oobconfig
adb uninstall --user 0 com.miui.analytics
adb uninstall --user 0 com.milink.service
adb uninstall --user 0 com.miui.cloudbackup
adb uninstall --user 0 com.miui.cloudservice.sysbase
adb uninstall --user 0 com.miui.compass
adb uninstall --user 0 com.google.android.apps.restore
adb uninstall --user 0 com.miui.fm
adb uninstall --user 0 com.miui.fmservice
adb uninstall --user 0 com.xiaomi.mipicks
adb uninstall --user 0 com.google.android.apps.subscriptions.red
adb uninstall --user 0 com.google.android.apps.subscriptions.red.LauncherActivity
adb uninstall --user 0 com.mi.healthglobal
adb uninstall --user 0 com.miui.micloudsync
adb uninstall --user 0 com.xiaomi.payment
adb uninstall --user 0 com.mipay.wallet.in
adb uninstall --user 0 org.mipay.android.manager
adb uninstall --user 0 com.miui.mishare.connectivity
adb uninstall --user 0 com.amazon.appmanager
adb uninstall --user 0 com.miui.notes
adb uninstall --user 0 com.xiaomi.scanner
adb uninstall --user 0 com.miui.miservice
adb uninstall --user 0 com.xiaomi.midrop
adb uninstall --user 0 com.miui.cloudservice
adb uninstall --user 0 com.miui.backup
adb uninstall --user 0 com.miui.bugreport
adb uninstall --user 0 com.bsp.catchlog
adb uninstall --user 0 com.xiaomi.mi_connect_service
adb uninstall --user 0 com.xiaomi.glgm
adb uninstall --user 0 com.miui.android.fashiongallery
adb uninstall --user 0 com.miui.yellowpage
adb uninstall --user 0 com.miui.hybrid.accessory
adb uninstall --user 0 com.miui.hybrid
adb uninstall --user 0 com.mi.android.globalminusscreen
adb uninstall --user 0 com.micredit.in
adb uninstall --user 0 cn.wps.xiaomi.abroad.lite
adb uninstall --user 0 com.miui.maintenancemode
adb uninstall --user 0 android.autoinstalls.config.Xiaomi.qssi
adb uninstall --user 0 com.google.android.setupwizard
adb uninstall --user 0 com.android.dreams.phototable
adb uninstall --user 0 com.miui.player
adb uninstall --user 0 com.debug.loggerui
adb uninstall --user 0 com.miui.touchassistant
adb uninstall --user 0 com.android.musicfx
adb uninstall --user 0 com.google.android.apps.safetyhub
adb uninstall --user 0 android.autoinstalls.config.Xiaomi.model
adb uninstall --user 0 com.xiaomi.simactivate.service
adb uninstall --user 0 com.google.android.adservices.api
adb uninstall --user 0 com.android.adservices.api
adb uninstall --user 0 com.miui.msa.global
adb uninstall --user 0 com.xiaomi.miplay_client
adb uninstall --user 0 com.xiaomi.dtool
adb uninstall --user 0 com.miui.daemon
adb uninstall --user 0 com.mi.globalbrowser
adb uninstall --user 0 com.mi.health
adb uninstall --user 0 com.android.email
adb uninstall --user 0 com.miui.huanji
adb uninstall --user 0 com.mfashiongallery.emag
adb uninstall --user 0 com.mipay.wallet
adb uninstall --user 0 com.android.browser
adb uninstall --user 0 com.miui.contentextension
adb uninstall --user 0 com.unionpay.tsmservice.mi
adb uninstall --user 0 com.miui.securityinputmethod
adb uninstall --user 0 com.miui.voiceassist
adb uninstall --user 0 com.miui.voicetrigger
adb uninstall --user 0 com.miui.tsmclient
adb uninstall --user 0 com.miui.carlink
adb uninstall --user 0 com.miui.nextpay
adb uninstall --user 0 com.miui.greenguard
adb uninstall --user 0 com.xiaomi.aiasst.service
adb uninstall --user 0 com.xiaomi.aiasst.vision
adb uninstall --user 0 com.xiaomi.mirror
adb uninstall --user 0 com.xiaomi.aireco
adb uninstall --user 0 com.mi.globalminusscreen
adb uninstall --user 0 com.miui.videoplayer
adb uninstall --user 0 com.miui.gallery
